sudo: false
language: php
php:
  - 5.6
  - 7
  - hhvm
before_script:
  - composer self-update
  - composer install
  - wget https://phar.phpunit.de/phpunit.phar
script:
  - php phpunit.phar --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
